[package]
name = "vigilansee"
version = "0.1.0"
edition = "2024"

[workspace]
resolver = "3"
members = ["vigilansee-parser", "vigilansee-api", "vigilansee-db"]

[dependencies]
tokio = { version = "1.50.0", features = ["full"] }
vigilansee-api = { path = "vigilansee-api" }
vigilansee-db = { path = "vigilansee-db" }


[workspace.dependencies]
dotenvy = "0.15"