name: Mirror to Epitech

on:
  push:
    branches:
      - main
      - dev

jobs:
  mirror:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan github.com >> ~/.ssh/known_hosts

      - name: Push to school repo
        run: |
          git remote add school git@github.com:EpitechPGE3-2025/G-EIP-600-TLS-6-1-eip-8.git
          git push school ${{ github.ref_name }}
